export const ADD_FORM_FIELD = "ADD_FORM_FIELD";
export const REMOVE_FORM_FIELD = "REMOVE_FORM_FIELD";
export const UPDATE_FORM_FIELDS = "UPDATE_FORM_FIELDS";
export const UPDATE_LABEL_NAME = "UPDATE_LABEL_NAME";
